app = 'cineray-mysql'
primary_region = 'gru'

[build]
  image = 'mysql:8.4'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048

[processes]
  app = '--datadir /data/mysql --mysql-native-password=ON'

[mounts]
  source = 'mysqldata'
  destination = '/data'

[env]
  MYSQL_DATABASE = 'cineray'
  MYSQL_USER = 'cineray'
