export const DEMO_CATALOG = [
  {
    key: "a_boca_do_diabo",
    tmdbId: 1481343,
    title: "A Boca do Diabo",
    synopsis: "Cinco amigos exploram as cavernas da Boca do Diabo, na Tailândia, para uma última aventura antes de começar a vida real. Mas logo descobrem que há algo mortal à espreita embaixo d'água.... veloz, silencioso e letal. Na escuridão sufocante, a confiança se desfaz, o pânico se espalha e cada passo errado se torna uma luta pela sobrevivência.",
    genre: "Terror, Thriller",
    rating: 6.535,
    runtime: "106 min",
    poster: "/2CZecxLrTSmzngWqIGganSMg6gK.jpg",
    backdrop: "/se8LfmZYFiNerF6U7zMUKePV0vE.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=2bp4Viru6Xc",
  },
  {
    key: "a_morte_de_robin_hood",
    tmdbId: 1284465,
    title: "A Morte de Robin Hood",
    synopsis: "Atormentado pelas cicatrizes de uma vida marcada pelo crime, Robin Hood sobrevive por pouco àquela que acreditava ser sua batalha final. Gravemente ferido, ele é encontrado por uma mulher misteriosa que o recolhe das sombras e passa a cuidar de seus ferimentos. Com o corpo fora de combate, cada erro cometido no passado volta para assombrá-lo.",
    genre: "Aventura, Drama, Ação",
    rating: 6.361,
    runtime: "129 min",
    poster: "/o0QndnepFPWget2kdKpzh26RBYt.jpg",
    backdrop: "/lh3BDkmWJh998n4fQcHYcVi7dpm.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=tlSDDuWxO_0",
  },
  {
    key: "a_morte_do_demonio_em_chamas",
    tmdbId: 1212763,
    title: "A Morte do Demônio: Em Chamas",
    synopsis: "Após a perda do marido, uma mulher busca consolo com seus sogros em sua casa isolada. À medida que, um a um, eles são transformados em Deadites — transformando o encontro em uma reunião familiar infernal —, ela descobre que os votos que fez em vida... continuam vivos mesmo após a morte.",
    genre: "Terror",
    rating: 7.871,
    runtime: "117 min",
    poster: "/fteLdvfRnltfLjAEnsl5E3vImnW.jpg",
    backdrop: "/biwEwIkjZhMUfXzz59bpeDzwYB6.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=RddZObTlmA8",
  },
  {
    key: "a_odisseia",
    tmdbId: 1368337,
    title: "A Odisseia",
    synopsis: "Acompanhe a saga de Odisseu, o lendário rei de Ítaca, em sua longa e perigosa jornada de retorno ao lar após a Guerra de Troia. O relato narra seus confrontos com seres míticos, como o ciclope Polifemo, as sedutoras sereias e a ninfa Calipso, enquanto ele luta contra o destino para se reencontrar com sua fiel esposa, Penélope.",
    genre: "Aventura, Ação, Fantasia",
    rating: 8,
    runtime: "172 min",
    poster: "/muMwJAiMtReEHLKpKMWt2rMkYF7.jpg",
    backdrop: "/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=AyIZ9tiiN8I",
  },
  {
    key: "a_ultima_casa",
    tmdbId: 1284041,
    title: "A Última Casa",
    synopsis: "Uma família trancada misteriosamente na própria casa precisa se unir para sobreviver à escassez de recursos e à força sombria que a mantém presa.",
    genre: "Terror, Ficção científica, Thriller",
    rating: 6.733,
    runtime: "110 min",
    poster: "/AqOwuZ4X0Ssi3LIsYqXNw52IIvW.jpg",
    backdrop: "/2mPmccLg8QCD4ZF6v8kSsUijPPW.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=MLxgaz2Zp1k",
  },
  {
    key: "avatar_aang_o_ultimo_mestre_do_ar",
    tmdbId: 980431,
    title: "Avatar Aang: O Último Mestre do Ar",
    synopsis: "O Avatar Aang, o último mestre do ar do mundo, toma conhecimento de um poder antigo que poderia salvar sua cultura da extinção. Com a ajuda de seus amigos, ele embarca em uma busca global para encontrá-lo antes que caia em mãos erradas e ameace destruir a paz que eles sacrificaram tudo para alcançar.",
    genre: "Animação, Ação, Aventura, Fantasia",
    rating: 9.3,
    runtime: "99 min",
    poster: "/h0jCyR6FTvp6ULcPokfoXvV1t3O.jpg",
    backdrop: "/ezbrL1dMymKQZw7mDEWa2ZTzN7d.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=7b20GRFZBFE",
  },
  {
    key: "backrooms_um_nao_lugar",
    tmdbId: 1083381,
    title: "Backrooms: Um Não-Lugar",
    synopsis: "Em 1990, o vendedor de móveis Clark descobre em sua loja um portal para os \"Backrooms\", um labirinto infinito de escritórios surreais. Fascinado, ele convence sua funcionária Kat e o namorado dela a mapearem as anomalias do local. Após o desaparecimento de Clark, sua terapeuta, a Dra. Mary Kline, mergulha na dimensão impossível para resgatá-lo, sendo forçada a confrontar seus próprios traumas enquanto busca uma saída.",
    genre: "Terror, Mistério, Ficção científica",
    rating: 7.1,
    runtime: "110 min",
    poster: "/a1pgQeEge47xrS4jGlDwIHiieVK.jpg",
    backdrop: "/dqmMWNWfLnExDRpMtIMqI97GQFR.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=0HjdiohVOik",
  },
  {
    key: "dia_d",
    tmdbId: 1275779,
    title: "Dia D",
    synopsis: "A existência de vida extraterrestre torna-se uma realidade inegável para todos os habitantes da Terra em um único instante. O mundo entra em colapso quando uma meteorologista, em plena transmissão ao vivo, é dominada por uma força invisível, perdendo a fala e emitindo sons perturbadores. Enquanto fenômenos inexplicáveis e sinais de controle mental em massa se espalham, um informante tenta expor segredos governamentais guardados por décadas. Diante da prova definitiva de que a humanidade não está sozinha, o pânico e o fascínio tomam conta de uma civilização confrontada pelo desconhecido.",
    genre: "Ficção científica, Thriller",
    rating: 7.436,
    runtime: "146 min",
    poster: "/pmff1wjKrgJi92PPr346lAifzlg.jpg",
    backdrop: "/flxau5Iu7bChQHsESqvGZ3FQRaI.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=icDuEHSxE-w",
  },
  {
    key: "homem_aranha_um_novo_dia",
    tmdbId: 969681,
    title: "Homem-Aranha: Um Novo Dia",
    synopsis: "É um novo dia para Peter Parker. Combatendo o crime em tempo integral como Homem-Aranha em um mundo que não se lembra mais dele e lidando com a pressão de ver seus antigos amigos seguirem em frente sem sua presença, Peter passa por uma mudança que talvez nem ele tenha o poder de controlar. Mas essa transformação também pode ser a única coisa capaz de deter uma surpreendente nova ameaça à cidade e às pessoas que ele ama: um poderoso vilão que ninguém sequer consegue enxergar.",
    genre: "Ficção científica, Ação, Aventura",
    rating: 7.865,
    runtime: "143 min",
    poster: "/x0nvYzQpyJc5pdT9lMnkMuYAg0O.jpg",
    backdrop: "/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=P3uI5sLosKU",
  },
  {
    key: "leviticus",
    tmdbId: 1564614,
    title: "Leviticus",
    synopsis: "Dois adolescentes precisam escapar de uma entidade violenta que assume a forma da pessoa que eles mais desejam — um ao outro.",
    genre: "Terror, Romance",
    rating: 6.671,
    runtime: "88 min",
    poster: "/5M2dI8TJeRNY3Aeidhp3Ujrb3aI.jpg",
    backdrop: "/7y8zWGEjs7tresw4Hzkkf4TdkcL.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=WXuK0vlFxII",
  },
  {
    key: "mestres_do_universo",
    tmdbId: 454639,
    title: "Mestres do Universo",
    synopsis: "Adam caiu na Terra quando era criança e perdeu a espada mágica que o ligava a Eternia. Quase 20 anos depois, ele a recupera e retorna ao seu planeta natal para protegê-lo do malvado Esqueleto, mas primeiro precisa desvendar seu passado.",
    genre: "Ação, Fantasia, Ficção científica",
    rating: 7.2,
    runtime: "133 min",
    poster: "/atpb7NKSyM4bJSUY8vQTunzK4Na.jpg",
    backdrop: "/yQIdU11DYQQp0neGtGtGxbGfRer.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=rJSmz-zhDxE",
  },
  {
    key: "minions_monstros",
    tmdbId: 1315772,
    title: "Minions & Monstros",
    synopsis: "Esta é a frenética, ridícula e totalmente verdadeira história de como os Minions conquistaram Hollywood, se tornaram estrelas de cinema, perderam tudo, libertaram monstros pelo mundo e, depois, se uniram para tentar salvar o planeta do caos que eles mesmos haviam acabado de criar.",
    genre: "Aventura, Animação, Comédia, Família, Fantasia",
    rating: 6.353,
    runtime: "87 min",
    poster: "/hTowtXrkCY7FJyoj4p91JckrJSE.jpg",
    backdrop: "/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=V-O-uBaHk3c",
  },
  {
    key: "moana",
    tmdbId: 1108427,
    title: "Moana",
    synopsis: "Na Polinésia Antiga, quando uma terrível maldição contraída por Maui chega à ilha de um impetuoso chefe, sua filha obstinada responde ao chamado do Oceano para procurar o semideus e consertar as coisas. Adaptação live-action do filme de animação da Disney de 2016 'Moana'",
    genre: "Família, Fantasia, Comédia, Aventura",
    rating: 6.034,
    runtime: "115 min",
    poster: "/eEsiTi19EYBluPQliS3CMnBgqTj.jpg",
    backdrop: "/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=EEz5xbzYPKI",
  },
  {
    key: "obsessao",
    tmdbId: 1339713,
    title: "Obsessão",
    synopsis: "Sem grandes pretensões, um romântico incurável compra um brinquedo que promete realizar desejos únicos. Ele quebra o artefato misterioso enquanto pede para conquistar a crush e consegue exatamente o que desejava, mas descobre que a consequência é sinistra.",
    genre: "Terror, Thriller",
    rating: 8.228,
    runtime: "100 min",
    poster: "/wUc6IDf5ChjM1UyQye21qFBeJY0.jpg",
    backdrop: "/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=TaaDkbG3I7g",
  },
  {
    key: "soulm8te",
    tmdbId: 1307118,
    title: "Soulm8te",
    synopsis: "Um homem adquire um androide com inteligência artificial para lidar com o luto de sua falecida esposa. No entanto, ao tentar criar uma parceira verdadeiramente senciente, ele acaba transformando, inadvertidamente, um robô inofensivo em uma alma gêmea mortal.",
    genre: "Terror, Ficção científica, Thriller",
    rating: 6.477,
    runtime: "99 min",
    poster: "/bNErActDctl6cdUGw9pnjSCmyhQ.jpg",
    backdrop: "/7t6f6VxA2ZXbbZSVctgt7bZG2DI.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=DF9I1wLlXbk",
  },
  {
    key: "supergirl",
    tmdbId: 1081003,
    title: "Supergirl",
    synopsis: "Quando um adversário implacável atinge alguém muito próximo dela, Kara Zor-El relutantemente une forças com uma companheira improvável em uma épica jornada interestelar de vingança e justiça.",
    genre: "Ação, Aventura, Ficção científica",
    rating: 6.741,
    runtime: "108 min",
    poster: "/qhXfLI1gDWaahzfHT0cb2CH61hO.jpg",
    backdrop: "/4X2YSe8PaYbsBqX3TDmmIU4vOju.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=tzlY8XD1CGg",
  },
  {
    key: "the_odyssey",
    tmdbId: 1698863,
    title: "The Odyssey",
    synopsis: "",
    genre: "Aventura, Fantasia, Ação",
    rating: 5.885,
    runtime: "86 min",
    poster: "/xBHCRB7zLIW41w8QskfwJhm32YF.jpg",
    backdrop: "/rOIaKlAX0SeNC25dFbM0y1mFsH6.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=wD5w48WT3uo",
  },
  {
    key: "todo_mundo_em_panico",
    tmdbId: 1273221,
    title: "Todo Mundo em Pânico",
    synopsis: "Vinte e seis anos depois de escaparem de um assassino mascarado suspeitosamente familiar, o Quarteto Fantástico está de volta à mira do criminoso, e nenhuma propriedade intelectual de filmes de terror está a salvo.",
    genre: "Comédia",
    rating: 6.458,
    runtime: "95 min",
    poster: "/y9yJd2qIIwhZcllHeKHsz5eRvNr.jpg",
    backdrop: "/xWBiXclrRmTggQHMRsIn84YHavs.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=cGgWAHXuTKc",
  },
  {
    key: "toy_story_5",
    tmdbId: 1084244,
    title: "Toy Story 5",
    synopsis: "O trabalho de Buzz, Woody, Jessie e do resto da gangue fica exponencialmente mais difícil quando eles enfrentam uma nova ameaça à diversão: a tecnologia.",
    genre: "Animação, Família, Comédia, Aventura",
    rating: 7.42,
    runtime: "100 min",
    poster: "/sssrBhdvDcczgMQYDc8oCoSuFEJ.jpg",
    backdrop: "/8sSKdEmlmqF4kJUd28SqthXC4yZ.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=QftAW9TTmuQ",
  },
  {
    key: "zona_zero",
    tmdbId: 1375646,
    title: "Zona Zero",
    synopsis: "De repente, um vírus que sofre mutações rápidas é liberado em uma conferência de biologia, forçando o isolamento imediato do local. A contaminação se espalha rapidamente, e os infectados não apenas atacam, eles evoluem de formas imprevisíveis e cada vez mais perigosas. Presos nesse confinamento, um grupo de sobreviventes precisa lutar pela própria vida enquanto, a cada minuto, as regras do jogo mudam.",
    genre: "Ação, Terror, Ficção científica",
    rating: 8.1,
    runtime: "122 min",
    poster: "/hWT5fHzVcxq06SuLfAWYVCrue7P.jpg",
    backdrop: "/cOKATn8lOcvVnOqqV5oYWaI9z2Z.jpg",
    trailerUrl: "https://www.youtube.com/watch?v=LW6dpj1uCK8",
  },
]

const IMG = 'https://image.tmdb.org/t/p'

export function demoPoster(path) {
  return `${IMG}/w500${path}`
}

export function demoBackdrop(path) {
  return `${IMG}/w1280${path}`
}
